name: SharkRank
version: 0.2.0
Author: Numixe & GiantRaven
main: it.sharkcraft.sharkrank.Main
commands:
        shkill:
          description: View Your Kills
	shdeath:
	  description: View Your Deaths
	money:
	  description: View Your Amount of Money
